version: "3.9"

services:
  backend:
    build:
      context: ../src/backend
      dockerfile: ../../deployment/Dockerfile.backend
    container_name: caltrack_backend
    ports:
      - "3000:3000"
    networks:
      - caltrack-network

  frontend:
    build:
      context: ../src/frontend
      dockerfile: ../../deployment/Dockerfile.frontend
    container_name: caltrack_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - caltrack-network

  prometheus:
    image: prom/prometheus
    container_name: caltrack_prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - caltrack-network

  grafana:
    image: grafana/grafana
    container_name: caltrack_grafana
    ports:
      - "3001:3000"
    networks:
      - caltrack-network

networks:
  caltrack-network:
    driver: bridge
